# Generated by Django 2.2.7 on 2019-11-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caapp', '0002_auto_20191115_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student'},
        ),
    ]
