# Generated by Django 2.2.7 on 2019-11-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caapp', '0003_auto_20191115_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'student'},
        ),
    ]
